version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data

  airflow:
    build:
      context: ./airflow
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/airflow/data
