FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt ./  # Certifique-se de que requirements.txt está no contexto
RUN pip install -r requirements.txt
COPY . .                  # Copie tudo no diretório frontend/
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
